const constants = {
  ADD_SELLING_ITEM: 'ADD_SELLING_ITEM',
  REQUEST_SELLING_ID: 'REQUEST_SELLING_ID',
  CLOSE_SELL: 'CLOSE_SELL',
  REMOVE_ITEM: 'REMOVE_ITEM',
  FULL_FILL_STOCK: 'FULL_FILL_STOCK',
  REQUEUST_STOCK: 'REQUEUST_STOCK',
  SET_ERROR_STOCK: 'SET_ERROR_STOCK',
  REQUEST_REPORT_INFOS: 'REQUEST_REPORT_INFOS',
  FULL_FILL_REPORT: 'FULL_FILL_REPORT',
  REMOVE_LOADING_REPORT: 'REMOVE_LOADING_REPORT',
  FULL_FILL_SELL_DETAIL: 'FULL_FILL_SELL_DETAIL'
};

export default constants;
